Client/Client/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        public DbSet<ClientModel> ClientDb { get; set; }//entre los triangulos va el nombre del modelo y despues va nombre de la tabla de la base de datos

    }
}

Client/Client/Models/ClientModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Models
{
    public class ClientModel
    {
        [Key]
        public int client_id { get; set; }

        [Required(ErrorMessage = "Enter the client name")]
        [Display(Name = "Client Name")]
        public string client_name { get; set; }

        [Required(ErrorMessage = "Enter if the client has a credit ")]
        [Display(Name = "Credit")]
        public string client_credit { get; set; }

        [Required(ErrorMessage = "Enter the client age")]
        [Display(Name = "Age")]
        [Range(20, 50)]
        public int client_age { get; set; }
  
        [Required(ErrorMessage = "Enter the client email")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Enter a valid email address")]
        public string client_email { get; set; }

    }
}

Client/Client/Models/ErrorViewModel.cs
using System;

namespace Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/Client/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Client.Controllers
{
    public class ClientController : Controller
    {


        private readonly ApplicationDbContext _db;

        public ClientController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index() //En INDEX haremos que liste a todos los empleados en la BD (READ)
        {
            var displaydata = _db.ClientDb.ToList();
            return View(displaydata);
        }
        [HttpGet]
        public async Task<IActionResult> Index(string searchString)
        {


           // var displaydata = _db.ClientDb.ToList();// es _db.nombre de la tabla

            var getClientdetail = from m in _db.ClientDb
                                  select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                getClientdetail = getClientdetail.Where(s => s.client_name.Contains(searchString));
            }


            return View(await getClientdetail.ToListAsync());
        }

        public async Task<ActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getClient = await _db.ClientDb.FindAsync(id);
            return View(getClient);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Create(ClientModel nuevo) //se le pasa algo del tipo del modelo!!!!!!!!!!!
        {
            if (ModelState.IsValid)
            {
                _db.Add(nuevo);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");

            }

            return View(nuevo);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }
            var getClient = await _db.ClientDb.FindAsync(id);
            return View(getClient);
        }

        //task es para una consulta asincrona
        [HttpPost]
        public async Task<ActionResult> Edit(ClientModel oldClient)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldClient);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return View(oldClient);
        }

        public async Task<ActionResult> Delete(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index");

            }
            var getClient = await _db.ClientDb.FindAsync(id);
            return View(getClient);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {

            var getClient = await _db.ClientDb.FindAsync(id);
            _db.ClientDb.Remove(getClient);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");


        }
    }
}

Client/Client/Views/Client/Create.cshtml
@model Client.Models.ClientModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ClientModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
 
            <div class="form-group">
                <label asp-for="client_name" class="control-label"></label>
                <input asp-for="client_name" class="form-control" />
                <span asp-validation-for="client_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="client_credit" class="control-label"></label>
                <input asp-for="client_credit" class="form-control" />
                <span asp-validation-for="client_credit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="client_age" class="control-label"></label>
                <input asp-for="client_age" class="form-control" />
                <span asp-validation-for="client_age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="client_email" class="control-label"></label>
                <input asp-for="client_email" class="form-control" />
                <span asp-validation-for="client_email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Client/Client/Views/Client/Delete.cshtml
@model Client.Models.ClientModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClientModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_credit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_credit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Client/Client/Views/Client/Detail.cshtml
@model Client.Models.ClientModel

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>ClientModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_credit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_credit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.client_email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.client_email)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Client/Client/Views/Client/Edit.cshtml
@model Client.Models.ClientModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ClientModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="client_id" class="control-label"></label>
                <input asp-for="client_id" class="form-control" readonly/>
                <span asp-validation-for="client_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="client_name" class="control-label"></label>
                <input asp-for="client_name" class="form-control" />
                <span asp-validation-for="client_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="client_credit" class="control-label"></label>
                <input asp-for="client_credit" class="form-control" />
                <span asp-validation-for="client_credit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="client_age" class="control-label"></label>
                <input asp-for="client_age" class="form-control" />
                <span asp-validation-for="client_age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="client_email" class="control-label"></label>
                <input asp-for="client_email" class="form-control" />
                <span asp-validation-for="client_email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Client/Client/Views/Client/Index.cshtml
@model IEnumerable<Client.Models.ClientModel>

@{
    ViewData["Title"] = "Index";
}
    <body>

        <form asp-controller="Client" asp-action="Index" method="get">
            <p>
                Nombre del cliente: <input type="text" name="SearchString">
                <input type="submit" value="Buscar" />

            </p>

        </form>

        <p>
            <a asp-action="Create" class="badge badge-info">Crear un nuevo cliente</a>
        </p>


        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.client_id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.client_name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.client_credit)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.client_age)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.client_email)
                    </th>
                    <th>
                        Opciones
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.client_id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.client_name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.client_credit)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.client_age)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.client_email)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.client_id }, new { @class = "btn btn-primary" }) |

                            @Html.ActionLink("Details", "Detail", new { id = item.client_id }, new { @class = "btn btn-success" }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.client_id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </body>

Client/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Client" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Client - <a asp-area="" asp-controller="Client" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>